import React, { useContext } from 'react';
import { Link } from 'react-router-dom';
import { Alert, Button, Card, CardContent, Grid, LinearProgress, Stack, Typography, Box } from '@mui/material';
import AssessmentIcon from '@mui/icons-material/Assessment';
import HealthAndSafetyIcon from '@mui/icons-material/HealthAndSafety';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AppStateContext } from '../App.jsx';

const CustomTooltip = ({ active, payload, themeMode }) => {
  if (active && payload && payload.length) {
    return (
      <Box 
        className="glass-panel" 
        sx={{ 
          p: 2, 
          borderRadius: '10px', 
          boxShadow: '0 8px 30px rgba(0,0,0,0.15)',
          background: themeMode === 'light' ? 'rgba(255,255,255,0.95)' : 'rgba(15,23,30,0.95)',
        }}
      >
        <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 0.5 }}>
          {payload[0].payload.disease}
        </Typography>
        <Typography variant="body2" color="primary.main" sx={{ fontWeight: 800 }}>
          Probability: {payload[0].value}%
        </Typography>
      </Box>
    );
  }
  return null;
};

export default function ResultsPage() {
  const { caseResult, mode } = useContext(AppStateContext);

  if (!caseResult) {
    return (
      <Box sx={{ py: 6, textAlign: 'center' }}>
        <Alert severity="info" variant="outlined" sx={{ maxWidth: 500, mx: 'auto', borderRadius: '12px' }}>
          No assessment completed yet. Please fill out the patient intake form to view results.
        </Alert>
        <Button component={Link} to="/intake" variant="contained" sx={{ mt: 3, px: 4, py: 1.5, borderRadius: '10px' }}>
          Go to Intake Form
        </Button>
      </Box>
    );
  }

  const diseaseData = caseResult.general.predictions.map((item) => ({
    disease: item.disease,
    probability: Math.round(item.probability * 100),
  }));

  return (
    <Stack spacing={4}>
      <div>
        <Typography variant="h4" sx={{ fontWeight: 850, mb: 1 }}>Assessment Results</Typography>
        <Typography color="text.secondary">Diagnostic probability ratings generated by the symptom screening agent.</Typography>
      </div>

      <Grid container spacing={3}>
        {caseResult.general.predictions.map((item) => {
          const isHighest = item.probability === Math.max(...caseResult.general.predictions.map(p => p.probability));
          return (
            <Grid item xs={12} md={4} key={item.disease}>
              <Card 
                variant="outlined" 
                sx={{ 
                  height: '100%',
                  borderColor: isHighest ? 'primary.main' : 'divider',
                  boxShadow: isHighest 
                    ? (mode === 'light' ? '0 10px 20px rgba(15,118,110,0.06)' : '0 12px 24px rgba(20,184,166,0.12)') 
                    : 'none',
                  position: 'relative',
                  overflow: 'hidden'
                }}
              >
                {isHighest && (
                  <Box 
                    sx={{ 
                      position: 'absolute', 
                      top: 0, 
                      left: 0, 
                      right: 0, 
                      height: 4, 
                      bgcolor: 'primary.main' 
                    }} 
                  />
                )}
                <CardContent sx={{ p: 3 }}>
                  <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 2 }}>
                    <Typography color="text.secondary" variant="caption" sx={{ fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                      {isHighest ? 'Primary Candidate' : 'Differential Diagnosis'}
                    </Typography>
                    <HealthAndSafetyIcon color={isHighest ? 'primary' : 'disabled'} />
                  </Stack>
                  <Typography variant="h5" sx={{ fontWeight: 800, mb: 2 }}>{item.disease}</Typography>
                  <LinearProgress 
                    variant="determinate" 
                    value={item.probability * 100} 
                    color={isHighest ? 'primary' : 'inherit'}
                    sx={{ 
                      my: 1.5, 
                      height: 10, 
                      borderRadius: 99,
                      bgcolor: mode === 'light' ? 'rgba(0,0,0,0.05)' : 'rgba(255,255,255,0.05)',
                    }} 
                  />
                  <Typography variant="body2" sx={{ fontWeight: 700, mt: 1 }}>
                    {Math.round(item.probability * 100)}% Probability
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          );
        })}
      </Grid>

      <Card variant="outlined">
        <CardContent sx={{ p: { xs: 2.5, md: 4 } }}>
          <Typography variant="h6" sx={{ mb: 3, fontWeight: 700 }}>Differential Risk Visualization</Typography>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={diseaseData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
              <defs>
                <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={mode === 'light' ? '#0f766e' : '#14b8a6'} stopOpacity={1}/>
                  <stop offset="100%" stopColor={mode === 'light' ? '#7c3aed' : '#a78bfa'} stopOpacity={0.25}/>
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={mode === 'light' ? 'rgba(0,0,0,0.05)' : 'rgba(255,255,255,0.05)'} />
              <XAxis dataKey="disease" stroke={mode === 'light' ? '#4b5563' : '#9ca3af'} tick={{ fontSize: 12, fontWeight: 600 }} />
              <YAxis domain={[0, 100]} stroke={mode === 'light' ? '#4b5563' : '#9ca3af'} tick={{ fontSize: 12, fontWeight: 600 }} />
              <Tooltip content={<CustomTooltip themeMode={mode} />} cursor={{ fill: mode === 'light' ? 'rgba(0,0,0,0.02)' : 'rgba(255,255,255,0.02)' }} />
              <Bar dataKey="probability" fill="url(#chartGradient)" radius={[8, 8, 0, 0]} barSize={55} />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>

      {caseResult.general.diabetes_triggered ? (
        <Card 
          variant="outlined" 
          sx={{ 
            borderColor: 'warning.main',
            background: mode === 'light' ? 'rgba(245,158,11,0.05)' : 'rgba(245,158,11,0.04)',
            borderWidth: '1.5px',
            borderRadius: '16px'
          }}
        >
          <CardContent sx={{ p: 3 }}>
            <Grid container spacing={3} alignItems="center" justifyContent="space-between">
              <Grid item xs={12} md={8}>
                <Typography variant="h6" color="warning.main" sx={{ fontWeight: 700, mb: 1, display: 'flex', alignItems: 'center', gap: 1 }}>
                  ⚠️ Diabetes Specialist Agent Activated
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Trigger reasons: {caseResult.general.trigger_reasons.join('; ')}
                </Typography>
              </Grid>
              <Grid item xs={12} md={4} sx={{ display: 'flex', justifyContent: { xs: 'flex-start', md: 'flex-end' } }}>
                <Button 
                  component={Link} 
                  to="/diabetes-report" 
                  variant="contained" 
                  color="secondary"
                  size="large"
                  startIcon={<AssessmentIcon />}
                  endIcon={<ArrowForwardIcon />}
                  sx={{ 
                    borderRadius: '10px',
                    px: 3.5,
                    boxShadow: '0 4px 14px rgba(124, 58, 237, 0.25)'
                  }}
                >
                  View Specialist Report
                </Button>
              </Grid>
            </Grid>
          </CardContent>
        </Card>
      ) : (
        <Alert 
          severity="success" 
          icon={<CheckCircleOutlineIcon fontSize="inherit" />}
          sx={{ 
            borderRadius: '16px', 
            p: 2.5,
            border: '1px solid',
            borderColor: 'success.light',
            bgcolor: mode === 'light' ? 'rgba(16,185,129,0.05)' : 'rgba(16,185,129,0.03)'
          }}
        >
          <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 0.5 }}>Diabetes Screen Negative</Typography>
          The specialist agent was not activated for this assessment as blood glucose, HbA1c, and XGBoost risk signals remained below trigger thresholds.
        </Alert>
      )}
    </Stack>
  );
}

